import { useState } from "react";
import { api } from "../api.js";
import { Button, Card, DataTable, ErrorMessage, Field, Loading, Notice, PageHeader, useAsync } from "../components.jsx";

const unitOptions = ["GRAM", "KG", "ML", "LITER", "PIECE", "PACKET", "BOX", "BOTTLE"];

export function InventoryPage({ ledger = false, adjustment = false, opening = false }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [refresh, setRefresh] = useState(0);
  const stock = useAsync(() => api("/inventory/stock").then((response) => response.data), [refresh]);
  const movements = useAsync(() => api("/inventory/ledger?limit=300").then((response) => response.data), [refresh]);
  const items = useAsync(() => api("/masters/items?limit=500").then((response) => response.data), []);
  const [form, setForm] = useState({ item: "", quantity: 1, unit: "KG", direction: "OUT", reason: "" });
  async function submit(event) {
    event.preventDefault(); setError("");
    try { await api(opening ? "/transactions/opening-stock" : "/transactions/stock-adjustments", { method: "POST", body: { ...form, quantity: Number(form.quantity) } }); setMessage(opening ? "Opening stock posted to the ledger." : "Stock adjustment posted to the ledger."); setRefresh((value) => value + 1); }
    catch (requestError) { setError(requestError.message); }
  }
  if (stock.loading || movements.loading || items.loading) return <Loading />;
  if (stock.error || movements.error || items.error) return <ErrorMessage message={stock.error || movements.error || items.error} />;
  if (adjustment || opening) return <><PageHeader title={opening ? "Opening Stock" : "Stock Adjustment"} description={opening ? "Load existing stock during ERP onboarding as an auditable opening-stock movement." : "Authorized corrections create traceable adjustment movements; stock is never edited directly."} />{message && <Notice>{message}</Notice>}<div className="two-column"><Card title={opening ? "Record opening stock" : "Post adjustment"}><form className="form-grid" onSubmit={submit}><Field label="Item" name="item" value={form.item} onChange={(event) => setForm({ ...form, item: event.target.value })} required options={items.data.map((item) => ({ value: item._id, label: `${item.itemCode} — ${item.name}` }))} />{!opening && <Field label="Direction" name="direction" value={form.direction} onChange={(event) => setForm({ ...form, direction: event.target.value })} options={[{ value: "IN", label: "Increase stock" }, { value: "OUT", label: "Decrease stock" }]} />}<Field label="Quantity" name="quantity" type="number" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} required /><Field label="Unit" name="unit" value={form.unit} onChange={(event) => setForm({ ...form, unit: event.target.value })} options={unitOptions} /><label className="field span-2"><span>{opening ? "Remarks" : "Reason"}</span><input value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} required /></label>{error && <div className="span-2"><ErrorMessage message={error} /></div>}<div className="form-actions span-2"><Button>{opening ? "Record opening stock" : "Post adjustment"}</Button></div></form></Card><Card title="Business rule"><p>Use this screen for opening stock and physical-stock corrections. Purchase receipts and sales invoices should be used for normal stock movements.</p></Card></div></>;
  if (ledger) return <><PageHeader title="Stock Ledger" description="Every inventory change is recorded with its previous and resulting base-unit balance." /><Card title="Latest movements"><DataTable rows={movements.data} columns={[{ key: "createdAt", label: "Date", render: (row) => new Date(row.createdAt).toLocaleString("en-IN") }, { key: "transactionNumber", label: "Transaction" }, { key: "transactionType", label: "Type", render: (row) => <span className="badge">{row.transactionType.replaceAll("_", " ")}</span> }, { key: "referenceNumber", label: "Reference" }, { key: "item.name", label: "Item" }, { key: "baseQuantity", label: "Movement" }, { key: "resultingStock", label: "Balance" }, { key: "createdBy.name", label: "User" }]} /></Card></>;
  return <><PageHeader title="Current Stock" description="Current balances are stored in each product's base unit for correct conversion and valuation." /><Card title="Inventory balances"><DataTable rows={stock.data} columns={[{ key: "item.itemCode", label: "Code" }, { key: "item.name", label: "Item" }, { key: "item.category", label: "Category" }, { key: "currentBaseQty", label: "Current stock", render: (row) => `${row.currentBaseQty} ${row.baseUnit}` }, { key: "averageCost", label: "Average cost", render: (row) => `₹${Number(row.averageCost).toFixed(2)}` }, { key: "stockValue", label: "Value", render: (row) => `₹${Number(row.stockValue).toFixed(2)}` }, { key: "reorderStatus", label: "Status", render: (row) => <span className={`badge ${row.reorderStatus === "LOW" ? "low" : ""}`}>{row.reorderStatus}</span> }]} /></Card></>;
}
