import cors from "cors";
import express from "express";
import morgan from "morgan";
import { env } from "./config/env.js";
import { dashboardRoutes } from "./routes/dashboardRoutes.js";
import { auditRoutes } from "./routes/auditRoutes.js";
import { authRoutes } from "./routes/authRoutes.js";
import { inventoryRoutes } from "./routes/inventoryRoutes.js";
import { masterRoutes } from "./routes/masterRoutes.js";
import { pdfRoutes } from "./routes/pdfRoutes.js";
import { reportRoutes } from "./routes/reportRoutes.js";
import { settingsRoutes } from "./routes/settingsRoutes.js";
import { transactionRoutes } from "./routes/transactionRoutes.js";
import { errorHandler, notFound } from "./middleware/errorHandler.js";

export const app = express();
app.use(cors({ origin: env.clientOrigin }));
app.use(express.json({ limit: "1mb" }));
app.use(morgan("dev"));
app.get("/api/health", (_req, res) => res.json({ status: "ok" }));
app.use("/api/auth", authRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api/audit", auditRoutes);
app.use("/api/masters", masterRoutes);
app.use("/api/transactions", transactionRoutes);
app.use("/api/inventory", inventoryRoutes);
app.use("/api/reports", reportRoutes);
app.use("/api/settings", settingsRoutes);
app.use("/api/pdf", pdfRoutes);
app.use(notFound);
app.use(errorHandler);
